In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)
pd.set_option("display.max_rows", 200)

In [3]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: None]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 200]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 120]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. Defaults to False,
    unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
    (if set to "1" for True, needs to be set before pandas is imported).
    [default: False] [currently: False]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
    (Deprecated, use `` instead.)
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype.
    [default: auto] [currently: auto]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).

    This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [4]:
File = "Project.csv"
df_raw = pd.read_csv(File)
print(df_raw.shape)
df_raw.head()

(2000, 11)

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
0,SH10000,Warehouse_MIA,San Francisco,UPS,10/2/2023,10/4/2023,25.7,67.46,Delivered,291,2
1,SH10001,Warehouse_MIA,Atlanta,DHL,12/6/2023,12/9/2023,38.9,268.85,Delivered,1225,3
2,SH10002,Warehouse_LA,Houston,DHL,9/18/2023,9/20/2023,37.2,74.35,Delivered,220,2
3,SH10003,Warehouse_BOS,Seattle,OnTrac,1/26/2023,2/4/2023,42.6,187.04,Delivered,1156,9
4,SH10004,Warehouse_SF,Dallas,OnTrac,6/3/2023,6/6/2023,7.9,120.01,Delivered,1017,3

In [5]:
df_raw.shape
df_raw.head()

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
0,SH10000,Warehouse_MIA,San Francisco,UPS,10/2/2023,10/4/2023,25.7,67.46,Delivered,291,2
1,SH10001,Warehouse_MIA,Atlanta,DHL,12/6/2023,12/9/2023,38.9,268.85,Delivered,1225,3
2,SH10002,Warehouse_LA,Houston,DHL,9/18/2023,9/20/2023,37.2,74.35,Delivered,220,2
3,SH10003,Warehouse_BOS,Seattle,OnTrac,1/26/2023,2/4/2023,42.6,187.04,Delivered,1156,9
4,SH10004,Warehouse_SF,Dallas,OnTrac,6/3/2023,6/6/2023,7.9,120.01,Delivered,1017,3

In [6]:
df_raw.dtypes

Shipment_ID          object
Origin_Warehouse     object
Destination          object
Carrier              object
Shipment_Date        object
Delivery_Date        object
Weight_kg           float64
Cost                float64
Status               object
Distance_miles        int64
Transit_Days          int64
dtype: object

In [7]:
df_raw["Shipment_ID"].dtype

dtype('O')

In [8]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment_ID       2000 non-null   object
 1   Origin_Warehouse  2000 non-null   object
 2   Destination       2000 non-null   object
 3   Carrier           2000 non-null   object
 4   Shipment_Date     2000 non-null   object
 5   Delivery_Date     1968 non-null   object
 6   Weight_kg         2000 non-null   float64
 7   Cost              1959 non-null   float64
 8   Status            2000 non-null   object
 9   Distance_miles    2000 non-null   int64
 10  Transit_Days      2000 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 172.0+ KB

In [9]:
df_raw[["Shipment_Date", "Delivery_Date"]].dtypes

Shipment_Date    object
Delivery_Date    object
dtype: object

In [10]:
df_raw["Shipment_ID"] = df_raw["Shipment_ID"].astype(str)

In [11]:
df_raw["Shipment_ID"].dtype

dtype('O')

In [12]:
df_raw["Shipment_Date"] = pd.to_datetime(df_raw["Shipment_Date"], errors="coerce")

In [13]:
df_raw["Delivery_Date"] = pd.to_datetime(df_raw["Delivery_Date"], errors="coerce")

In [14]:
df_raw["Shipment_Date"].dtype
df_raw["Delivery_Date"].dtype

dtype('<M8[ns]')

In [15]:
df_raw["Delivery_Date"].isna().sum()

np.int64(32)

In [16]:
df_raw["Transit_Days"].isna().sum()

np.int64(0)

In [17]:
df_raw[df_raw["Delivery_Date"].isna()]["Status"].value_counts()

Status
Delivered    27
Delayed       5
Name: count, dtype: int64

In [18]:
df_raw[df_raw["Status"] == "Delivered"]["Delivery_Date"].isna().sum()

np.int64(27)

In [19]:
(df_raw["Delivery_Date"] - df_raw["Shipment_Date"]).dt.days.describe()

count    1968.000000
mean        4.618394
std         4.370629
min       -30.000000
25%         3.000000
50%         4.000000
75%         6.000000
max        20.000000
dtype: float64

In [20]:
df_raw["Transit_Days"].describe()

count    2000.000000
mean        4.182500
std         1.837902
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max        12.000000
Name: Transit_Days, dtype: float64

In [21]:
bad_mask = (df_raw["Delivery_Date"] - df_raw["Shipment_Date"]).dt.days < 0

In [22]:
bad_mask.sum()

np.int64(16)

In [23]:
df_raw.loc[bad_mask, "Delivery_Date"] = (
    df_raw.loc[bad_mask, "Shipment_Date"] +
    pd.to_timedelta(df_raw.loc[bad_mask, "Transit_Days"], unit="D")
)

In [24]:
(df_raw["Delivery_Date"] - df_raw["Shipment_Date"]).dt.days

0       2.0
1       3.0
2       2.0
3       9.0
4       3.0
       ...
1995    5.0
1996    5.0
1997    6.0
1998    5.0
1999    NaN
Length: 2000, dtype: float64

In [25]:
diff = (df_raw["Delivery_Date"] - df_raw["Shipment_Date"]).dt.days - df_raw["Transit_Days"]

In [26]:
diff.describe()

count    1968.000000
mean        0.707825
std         2.439403
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        13.000000
dtype: float64

In [27]:
df_raw["Estimated_Delivery_Date"] = (
    df_raw["Shipment_Date"] +
    pd.to_timedelta(df_raw["Transit_Days"], unit="D")
)

In [28]:
df_raw.shape

(2000, 12)

In [29]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Shipment_ID              2000 non-null   object
 1   Origin_Warehouse         2000 non-null   object
 2   Destination              2000 non-null   object
 3   Carrier                  2000 non-null   object
 4   Shipment_Date            2000 non-null   datetime64[ns]
 5   Delivery_Date            1968 non-null   datetime64[ns]
 6   Weight_kg                2000 non-null   float64
 7   Cost                     1959 non-null   float64
 8   Status                   2000 non-null   object
 9   Distance_miles           2000 non-null   int64
 10  Transit_Days             2000 non-null   int64
 11  Estimated_Delivery_Date  2000 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(5)
memory usage: 187.6+ KB

In [30]:
df_raw

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days,Estimated_Delivery_Date
0,SH10000,Warehouse_MIA,San Francisco,UPS,2023-10-02,2023-10-04,25.7,67.46,Delivered,291,2,2023-10-04
1,SH10001,Warehouse_MIA,Atlanta,DHL,2023-12-06,2023-12-09,38.9,268.85,Delivered,1225,3,2023-12-09
2,SH10002,Warehouse_LA,Houston,DHL,2023-09-18,2023-09-20,37.2,74.35,Delivered,220,2,2023-09-20
3,SH10003,Warehouse_BOS,Seattle,OnTrac,2023-01-26,2023-02-04,42.6,187.04,Delivered,1156,9,2023-02-04
4,SH10004,Warehouse_SF,Dallas,OnTrac,2023-06-03,2023-06-06,7.9,120.01,Delivered,1017,3,2023-06-06
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,SH11995,Warehouse_BOS,San Francisco,FedEx,2023-01-18,2023-01-23,7.9,217.78,Delivered,1616,5,2023-01-23
1996,SH11996,Warehouse_HOU,Phoenix,UPS,2023-10-27,2023-11-01,36.5,279.47,Delivered,1708,5,2023-11-01
1997,SH11997,Warehouse_HOU,Portland,LaserShip,2023-02-13,2023-02-19,11.4,250.32,Delivered,1912,6,2023-02-19
1998,SH11998,Warehouse_SEA,Detroit,USPS,2023-10-17,2023-10-22,10.9,272.31,Delivered,2188,5,2023-10-22
1999,SH11999,Warehouse_MIA,Portland,OnTrac,2023-07-08,NaT,49.5,360.74,Delivered,2321,7,2023-07-15

In [31]:
df_raw["Cost"].isnull().value_counts()

Cost
False    1959
True       41
Name: count, dtype: int64

In [32]:
df_raw[df_raw["Cost"].isna()]["Status"].value_counts()

Status
Delivered    36
Delayed       5
Name: count, dtype: int64

In [33]:
df_raw[["Cost", "Distance_miles", "Weight_kg"]].corr()

                    Cost  Distance_miles  Weight_kg
Cost            1.000000        0.435586     0.0212
Distance_miles  0.435586        1.000000    -0.0097
Weight_kg       0.021200       -0.009700     1.0000

In [34]:
df_raw.groupby("Carrier")["Cost"].mean()

Carrier
Amazon Logistics    193.909251
DHL                 222.134764
FedEx               217.965952
LaserShip           207.857905
OnTrac              184.599017
UPS                 229.714542
USPS                182.661032
Name: Cost, dtype: float64

In [35]:
df_raw[df_raw["Cost"].isna()]["Carrier"].value_counts()

Carrier
USPS                11
LaserShip            7
Amazon Logistics     7
DHL                  6
UPS                  5
OnTrac               4
FedEx                1
Name: count, dtype: int64

In [36]:
df_raw["Cost_per_Mile"] = df_raw["Cost"] / df_raw["Distance_miles"]

In [37]:
carrier_cpm = df_raw.groupby("Carrier")["Cost_per_Mile"].mean()

In [38]:
df_raw.groupby("Carrier")["Cost_per_Mile"].describe()

                  count      mean       std       min       25%       50%       75%       max
Carrier
Amazon Logistics  267.0  0.171177  0.088489  0.114025  0.132619  0.147827  0.166607  0.888333
DHL               275.0  0.187965  0.068654  0.016644  0.152993  0.169636  0.201124  0.869141
FedEx             294.0  0.185665  0.105694  0.014061  0.146001  0.161747  0.190590  1.652720
LaserShip         296.0  0.184041  0.206184  0.012293  0.135054  0.151411  0.184717  3.379099
OnTrac            295.0  0.173136  0.085505  0.012395  0.135542  0.148712  0.179254  1.075069
UPS               251.0  0.186957  0.162009  0.117416  0.140099  0.156746  0.186137  2.501655
USPS              281.0  0.159827  0.069115  0.108254  0.128491  0.144197  0.166800  0.899667

In [39]:
df_raw["Carrier_Median_CPM"] = (
    df_raw.groupby("Carrier")["Cost_per_Mile"].transform("median")
)

In [40]:
df_raw.loc[df_raw["Cost"].isna(), "Cost"] = (
    df_raw.loc[df_raw["Cost"].isna(), "Distance_miles"] *
    df_raw.loc[df_raw["Cost"].isna(), "Carrier_Median_CPM"]
)

In [41]:
df_raw["Cost"].isna().sum()

np.int64(0)

In [42]:
df_raw["Cost"].describe()

count    2000.000000
mean      204.536370
std       220.864973
min        14.563905
25%       117.725000
50%       196.065000
75%       271.865000
max      6562.210000
Name: Cost, dtype: float64

In [43]:
df_raw.isnull().sum()

Shipment_ID                 0
Origin_Warehouse            0
Destination                 0
Carrier                     0
Shipment_Date               0
Delivery_Date              32
Weight_kg                   0
Cost                        0
Status                      0
Distance_miles              0
Transit_Days                0
Estimated_Delivery_Date     0
Cost_per_Mile              41
Carrier_Median_CPM          0
dtype: int64

In [44]:
df_raw["Cost_per_Mile"] = df_raw["Cost"] / df_raw["Distance_miles"]

In [45]:
df_raw["Cost_per_Mile"].isnull().sum()

np.int64(0)

In [46]:
df_raw.isnull().sum()

Shipment_ID                 0
Origin_Warehouse            0
Destination                 0
Carrier                     0
Shipment_Date               0
Delivery_Date              32
Weight_kg                   0
Cost                        0
Status                      0
Distance_miles              0
Transit_Days                0
Estimated_Delivery_Date     0
Cost_per_Mile               0
Carrier_Median_CPM          0
dtype: int64

In [48]:
df_raw["Delay_Days"] = (
    df_raw["Delivery_Date"] - df_raw["Estimated_Delivery_Date"]
).dt.days

In [49]:
df_raw["On_Time"] = df_raw["Delay_Days"] <= 0

In [51]:
df_raw.groupby("Carrier")["On_Time"].mean()

Carrier
Amazon Logistics    0.868613
DHL                 0.836299
FedEx               0.915254
LaserShip           0.897690
OnTrac              0.889632
UPS                 0.878906
USPS                0.921233
Name: On_Time, dtype: float64

In [52]:
df_delivered = df_raw[df_raw["Status"] == "Delivered"].copy()

df_delivered.groupby("Carrier")["On_Time"].mean()

Carrier
Amazon Logistics    0.995392
DHL                 0.974026
FedEx               0.995902
LaserShip           0.979839
OnTrac              0.983871
UPS                 0.968326
USPS                0.987448
Name: On_Time, dtype: float64

In [53]:
carrier_summary = df_delivered.groupby("Carrier").agg(
    Shipment_Count=("Shipment_ID", "count"),
    On_Time_Pct=("On_Time", "mean"),
    Avg_Cost=("Cost", "mean"),
    Total_Spend=("Cost", "sum"),
    Median_CPM=("Cost_per_Mile", "median")
).reset_index()

carrier_summary.sort_values("Total_Spend", ascending=False)

            Carrier  Shipment_Count  On_Time_Pct    Avg_Cost   Total_Spend  Median_CPM
2             FedEx             244     0.995902  220.287500  53750.150069    0.160878
5               UPS             221     0.968326  240.118601  53066.210742    0.155106
3         LaserShip             248     0.979839  208.642760  51743.404458    0.151411
1               DHL             231     0.974026  223.574342  51645.672926    0.169636
4            OnTrac             248     0.983871  183.410589  45485.826173    0.148712
6              USPS             239     0.987448  182.439323  43602.998139    0.144062
0  Amazon Logistics             217     0.995392  197.794171  42921.335025    0.147827

In [55]:
carrier_summary["Cost_Level"] = np.where( carrier_summary["Avg_Cost"] > carrier_summary["Avg_Cost"].mean(), "High Cost", "Low Cost" )

In [56]:
carrier_summary["Reliability_Level"] = np.where( carrier_summary["On_Time_Pct"] > carrier_summary["On_Time_Pct"].mean(), "High Reliability", "Lower Reliability" )

In [57]:
carrier_summary

            Carrier  Shipment_Count  On_Time_Pct    Avg_Cost   Total_Spend  Median_CPM Cost_Level  Reliability_Level
0  Amazon Logistics             217     0.995392  197.794171  42921.335025    0.147827   Low Cost   High Reliability
1               DHL             231     0.974026  223.574342  51645.672926    0.169636  High Cost  Lower Reliability
2             FedEx             244     0.995902  220.287500  53750.150069    0.160878  High Cost   High Reliability
3         LaserShip             248     0.979839  208.642760  51743.404458    0.151411  High Cost  Lower Reliability
4            OnTrac             248     0.983871  183.410589  45485.826173    0.148712   Low Cost   High Reliability
5               UPS             221     0.968326  240.118601  53066.210742    0.155106  High Cost  Lower Reliability
6              USPS             239     0.987448  182.439323  43602.998139    0.144062   Low Cost   High Reliability

In [60]:
df_delivered["Distance_Bucket"] = pd.cut(
    df_delivered["Distance_miles"],
    bins=[0,300,600,900,float("inf")],
    labels=["0-300","301-600","601-900","900+"]
)

In [61]:
bucket_summary = df_delivered.groupby(
    ["Distance_Bucket", "Carrier"]
).agg(
    Shipments=("Shipment_ID", "count"),
    Avg_Cost=("Cost", "mean"),
    On_Time_Pct=("On_Time", "mean"),
    Median_CPM=("Cost_per_Mile", "median")
).reset_index()

bucket_summary.sort_values(["Distance_Bucket", "Shipments"], ascending=[True, False])

C:\Users\utkar\AppData\Local\Temp\ipykernel_11252\915303745.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bucket_summary = df_delivered.groupby(

   Distance_Bucket           Carrier  Shipments    Avg_Cost  On_Time_Pct  Median_CPM
3            0-300         LaserShip         30   58.372376     1.000000    0.248230
1            0-300               DHL         24   54.912447     1.000000    0.256800
0            0-300  Amazon Logistics         23   67.553913     1.000000    0.308198
4            0-300            OnTrac         23   63.630000     0.956522    0.225393
6            0-300              USPS         19   42.133890     1.000000    0.191745
2            0-300             FedEx         17   68.008235     0.941176    0.361093
5            0-300               UPS         16   62.138750     0.937500    0.277150
11         301-600            OnTrac         38   90.854737     0.973684    0.197555
13         301-600              USPS         34   78.575047     0.970588    0.156095
10         301-600         LaserShip         29   90.581724     0.896552    0.198032
12         301-600               UPS         26   90.140385     0.961538    0.207142
9          301-600             FedEx         23   92.983043     1.000000    0.223766
8          301-600               DHL         21   97.611429     1.000000    0.214404
7          301-600  Amazon Logistics         16   83.518019     1.000000    0.172174
17         601-900         LaserShip         35  128.683714     0.971429    0.162145
16         601-900             FedEx         33  149.218790     1.000000    0.173001
20         601-900              USPS         33  141.603367     1.000000    0.153284
18         601-900            OnTrac         31  125.679355     1.000000    0.157727
15         601-900               DHL         26  153.610885     0.961538    0.204100
14         601-900  Amazon Logistics         25  124.588834     1.000000    0.159723
19         601-900               UPS         24  134.048750     0.958333    0.163170
23            900+             FedEx        171  266.264211     1.000000    0.154244
22            900+               DHL        160  276.775320     0.968750    0.161477
25            900+            OnTrac        156  235.088437     0.987179    0.140995
26            900+               UPS        155  300.072069     0.974194    0.146642
24            900+         LaserShip        154  278.320995     0.993506    0.141012
21            900+  Amazon Logistics        153  241.284875     0.993464    0.138386
27            900+              USPS        153  231.751579     0.986928    0.133016

In [62]:
df_delivered.to_csv("carrier_optimization_analysis.csv", index=False)

In [64]:
df_delivered.to_csv(r"C:\Users\utkar\OneDrive\Desktop\carrier_optimization_analysis.csv", index=False)